import Head from 'next/head'
import Image from 'next/image'
import { HeroBanner, Footer } from '../components'

const Home = () => {
  return (
    <>
      <Head>
        <title>Phonex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* hero banner */}
      <HeroBanner />
      <div className='products-heading'>
        <h2>Best Selling Products</h2>
        <p>Speakers of many variations</p>
      </div>
      <div className='products-container'>
        {["Product 1", "Product 2"].map((product) => product)}
      </div>
      {/* footer */}
    </>
  )
}

export default Home;